### ISSUE TITLE
Why is the board Y axis inverted?

### ISSUE THREAD

**Issue by pydo** [BattlesnakeOfficial/engine#5]
Was it an intentional design feature to invert the Y axis of the board?
If not, I'm guessing removing it would be a pretty huge breaking change.

**Comment by bvanvugt** [comment]
Hah, @chris-bsnake and I we were just talking about this today :)

It's a decision we made a loooong time ago to match pixel display systems (which place the origin top left) instead of standard cartesian (origin at bottom left). Older versions of the API sent the entire game board as a 2D array, so iterating over the board felt more natural this way. Since then we've reduced the payload sent in the API, and now it feels... awkward.

Honestly we'd like to change it, and we'll likely include it in the next breaking API change. But alone, it's just not worth the disruption.

**Comment by bvanvugt** [comment]
See https://github.com/BattlesnakeOfficial/rules/issues/4
